# Change these first
owner: bracke # Your GitHub organization or username, where this repository lives
repo: sitemonitor # The name of this repository

sites:
  - name: bracke.dk
    url: https://bracke.dk
  - name: Bracke http
    url: http://bracke.dk
  - name: evoluxos.com
    url: https://evoluxos.com
  - name: evoluxos.com http
    url: https://evoluxos.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /sitemonitor
  logoUrl: https://avatars.githubusercontent.com/u/627383?s=96&v=4
  name: Sitemonitor
  introTitle: "Uptime monitor and status page"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
